/* tslint:disable */
/* eslint-disable */
/**
 * blog/blog.proto
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: version not set
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { V1NewBlog } from './V1NewBlog';
import {
    V1NewBlogFromJSON,
    V1NewBlogFromJSONTyped,
    V1NewBlogToJSON,
} from './V1NewBlog';

/**
 * 
 * @export
 * @interface V1CreateRequest
 */
export interface V1CreateRequest {
    /**
     * 
     * @type {V1NewBlog}
     * @memberof V1CreateRequest
     */
    blog?: V1NewBlog;
}

/**
 * Check if a given object implements the V1CreateRequest interface.
 */
export function instanceOfV1CreateRequest(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function V1CreateRequestFromJSON(json: any): V1CreateRequest {
    return V1CreateRequestFromJSONTyped(json, false);
}

export function V1CreateRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): V1CreateRequest {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'blog': !exists(json, 'blog') ? undefined : V1NewBlogFromJSON(json['blog']),
    };
}

export function V1CreateRequestToJSON(value?: V1CreateRequest | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'blog': V1NewBlogToJSON(value.blog),
    };
}

