/* tslint:disable */
/* eslint-disable */
/**
 * blog/blog.proto
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: version not set
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface V1Blog
 */
export interface V1Blog {
    /**
     * 
     * @type {number}
     * @memberof V1Blog
     */
    id?: number;
    /**
     * 
     * @type {string}
     * @memberof V1Blog
     */
    title?: string;
    /**
     * 
     * @type {string}
     * @memberof V1Blog
     */
    image?: string;
    /**
     * 
     * @type {string}
     * @memberof V1Blog
     */
    summary?: string;
    /**
     * 
     * @type {string}
     * @memberof V1Blog
     */
    markdown?: string;
    /**
     * 
     * @type {string}
     * @memberof V1Blog
     */
    author?: string;
    /**
     * 
     * @type {Date}
     * @memberof V1Blog
     */
    createdAt?: Date;
    /**
     * 
     * @type {Date}
     * @memberof V1Blog
     */
    updatedAt?: Date;
}

/**
 * Check if a given object implements the V1Blog interface.
 */
export function instanceOfV1Blog(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function V1BlogFromJSON(json: any): V1Blog {
    return V1BlogFromJSONTyped(json, false);
}

export function V1BlogFromJSONTyped(json: any, ignoreDiscriminator: boolean): V1Blog {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': !exists(json, 'id') ? undefined : json['id'],
        'title': !exists(json, 'title') ? undefined : json['title'],
        'image': !exists(json, 'image') ? undefined : json['image'],
        'summary': !exists(json, 'summary') ? undefined : json['summary'],
        'markdown': !exists(json, 'markdown') ? undefined : json['markdown'],
        'author': !exists(json, 'author') ? undefined : json['author'],
        'createdAt': !exists(json, 'createdAt') ? undefined : (new Date(json['createdAt'])),
        'updatedAt': !exists(json, 'updatedAt') ? undefined : (new Date(json['updatedAt'])),
    };
}

export function V1BlogToJSON(value?: V1Blog | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'id': value.id,
        'title': value.title,
        'image': value.image,
        'summary': value.summary,
        'markdown': value.markdown,
        'author': value.author,
        'createdAt': value.createdAt === undefined ? undefined : (value.createdAt.toISOString()),
        'updatedAt': value.updatedAt === undefined ? undefined : (value.updatedAt.toISOString()),
    };
}

