/* tslint:disable */
/* eslint-disable */
/**
 * blog/blog.proto
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: version not set
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { V1Blog } from './V1Blog';
import {
    V1BlogFromJSON,
    V1BlogFromJSONTyped,
    V1BlogToJSON,
} from './V1Blog';

/**
 * 
 * @export
 * @interface V1ListResponse
 */
export interface V1ListResponse {
    /**
     * 
     * @type {Array<V1Blog>}
     * @memberof V1ListResponse
     */
    blogs?: Array<V1Blog>;
}

/**
 * Check if a given object implements the V1ListResponse interface.
 */
export function instanceOfV1ListResponse(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function V1ListResponseFromJSON(json: any): V1ListResponse {
    return V1ListResponseFromJSONTyped(json, false);
}

export function V1ListResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): V1ListResponse {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'blogs': !exists(json, 'blogs') ? undefined : ((json['blogs'] as Array<any>).map(V1BlogFromJSON)),
    };
}

export function V1ListResponseToJSON(value?: V1ListResponse | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'blogs': value.blogs === undefined ? undefined : ((value.blogs as Array<any>).map(V1BlogToJSON)),
    };
}

