/* tslint:disable */
/* eslint-disable */
/**
 * blog/blog.proto
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: version not set
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { V1Blog } from './V1Blog';
import {
    V1BlogFromJSON,
    V1BlogFromJSONTyped,
    V1BlogToJSON,
} from './V1Blog';

/**
 * 
 * @export
 * @interface V1UpdateResponse
 */
export interface V1UpdateResponse {
    /**
     * 
     * @type {V1Blog}
     * @memberof V1UpdateResponse
     */
    blog?: V1Blog;
}

/**
 * Check if a given object implements the V1UpdateResponse interface.
 */
export function instanceOfV1UpdateResponse(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function V1UpdateResponseFromJSON(json: any): V1UpdateResponse {
    return V1UpdateResponseFromJSONTyped(json, false);
}

export function V1UpdateResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): V1UpdateResponse {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'blog': !exists(json, 'blog') ? undefined : V1BlogFromJSON(json['blog']),
    };
}

export function V1UpdateResponseToJSON(value?: V1UpdateResponse | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'blog': V1BlogToJSON(value.blog),
    };
}

