/* tslint:disable */
/* eslint-disable */
/**
 * empty-blog
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface NewBlog
 */
export interface NewBlog {
    /**
     * 
     * @type {string}
     * @memberof NewBlog
     */
    author: string;
    /**
     * 
     * @type {string}
     * @memberof NewBlog
     */
    image: string;
    /**
     * 
     * @type {string}
     * @memberof NewBlog
     */
    markdown: string;
    /**
     * 
     * @type {string}
     * @memberof NewBlog
     */
    summary: string;
    /**
     * 
     * @type {string}
     * @memberof NewBlog
     */
    title: string;
}

/**
 * Check if a given object implements the NewBlog interface.
 */
export function instanceOfNewBlog(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "author" in value;
    isInstance = isInstance && "image" in value;
    isInstance = isInstance && "markdown" in value;
    isInstance = isInstance && "summary" in value;
    isInstance = isInstance && "title" in value;

    return isInstance;
}

export function NewBlogFromJSON(json: any): NewBlog {
    return NewBlogFromJSONTyped(json, false);
}

export function NewBlogFromJSONTyped(json: any, ignoreDiscriminator: boolean): NewBlog {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'author': json['author'],
        'image': json['image'],
        'markdown': json['markdown'],
        'summary': json['summary'],
        'title': json['title'],
    };
}

export function NewBlogToJSON(value?: NewBlog | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'author': value.author,
        'image': value.image,
        'markdown': value.markdown,
        'summary': value.summary,
        'title': value.title,
    };
}

